[project]
name = "foo"
version = "0.0.1"
description = ""
authors = [{name = "Frost Ming", email = "mianghong@gmail.com"}]
requires-python = ">=3.7"
readme = "README.md"
dependencies = [
    "click",
]
license = {text = "MIT"}

[build-system]
requires = ["flit_core>=3.2,<4"]
build-backend = "flit_core.buildapi"
